### ISSUE TITLE
Error in order.component.ts:5

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/openslides.com#79]
Error after run "npm install" and "npm start":

ERROR in src/app/order/order.component.ts:5:35 - error TS2306: File '/home/emanuel/projects/openslides/src/openslides.com/node_modules/@angular/material/index.d.ts' is not a module.

5 import { MatCheckboxChange } from '@angular/material';

**Comment by bernhardreiter** [comment]
Cannot reproduce with current head 25d62afe4a77d9246a54faa87e274780f09fd971 with a fresh build. (On Debian Buster standard Buster npm and nodejs). 

So maybe a full fresh build can fix it or it depends on a special version.

**Comment by jsangmeister** [comment]
This was in the livestream branch and came from a missing rebase. Fixed now
